# 主动抛出异常
# raise TypeError("haha is error")

# 断言
